runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /.*
  script: multiuser_blog.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
